# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/packages/build'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/dev-env'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/e2e'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/graal-type-introspection'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/yamjs-core'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/yamjs-dev-reload'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/yamjs-legacy'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/yamjs-test-util'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'gradle'
    directory: '/packages/yamjs-plugin'
    schedule:
      interval: 'weekly'
