# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build Artifacts
on:
  release:
    types: [published]
  workflow_dispatch:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build projects
      run: |
        export MAIN_DIR=$(pwd)
        cd ${GITHUB_WORKSPACE}
        chmod +x ./gradlew
        ./gradlew shadowJar
        cd ${MAIN_DIR}
        cp ${GITHUB_WORKSPACE}/paper/build/libs/paper-all.jar ./yamjs-paper.jar
    - name: Publish to GitHub Packages
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./yamjs-paper.jar
